CREATE TABLE E_BOOK
(CALLNO VARCHAR(15),
E_NAME VARCHAR(200),
AUTHOR VARCHAR(200),
PUBLISHER VARCHAR(200),
QUANTITY int, 
ISSUED int,
CONSTRAINT E_BOOK_PK PRIMARY KEY (CALLNO));


CREATE TABLE E_LIBRARIAN 
(ID int,
NAME VARCHAR(200),
PASSWORD VARCHAR(100), 
EMAIL VARCHAR(100), 
MOBILE long, 
CONSTRAINT E_LIBRARIAN_PK PRIMARY KEY (ID)
);


CREATE TABLE  E_ISSUEBOOK
(CALLNO VARCHAR(15) NOT NULL, 
STUDENTID VARCHAR(100) NOT NULL, 
STUDENTNAME VARCHAR(200), 
STUDENTMOBILE long, 
ISSUEDDATE DATE, 
RETURNSTATUS VARCHAR(4000)
);

select * from E_LIBRARIAN;
select * from E_BOOK;
select * from E_ISSUEBOOK;


